site_name: Spot the Docs
site_url: https://floating-citadel-84168.herokuapp.com/
repo_name: GitHub
repo_url: https://github.com/billimarie/spot-the-docs/
site_description: Spot the Docs is a lightweight Laravel/Heroku web app that finds open-source projects with documentation issues using GitHub's API.
site_author: Billimarie Lubiano Robinson
theme: yeti
pages:
  - Home: 'index.md'
  - About: 'about.md'
